version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=mysql  # Use service name after network connection
      - MYSQL_PORT=3306   # Internal MySQL port
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=cms_db
    networks:
      - cms-network
networks:
  cms-network:
    driver: bridge