version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=172.21.0.2  # Update to the new IP from inspect
      - MYSQL_PORT=3307       # Match the host port mapping
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=cms_db
    networks:
      - cms-network
networks:
  cms-network:
    driver: bridge