version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Changed to avoid Jenkins on 8080
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql  # Placeholder, will adjust
    networks:
      - cms-network
  # Remove mysql and phpmyadmin services since they exist
volumes:
  # No mysql-data volume needed if reusing existing MySQL
networks:
  cms-network:
    driver: bridge