
version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: cms_web
    ports:
      - "8010:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: test_db_1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
