version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=host.docker.internal 
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=cms_db
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge
