version: '3.8'

services:
  web:
    build: .
    ports:
      - "8082:80"   # CMS will now run at localhost:8082 to avoid conflict with Jenkins
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - cmsnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cmsnet

volumes:
  db_data:

networks:
  cmsnet:
