version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql  # Will adjust to existing MySQL IP/port later
    networks:
      - cms-network
networks:
  cms-network:
    driver: bridge